import { test, expect } from '@playwright/test';
const origin = 'http://127.0.0.1:3100';
const headers = { Origin: origin };
const tinyPng = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/lJ0AAAAASUVORK5CYII=', 'base64');

test('seller can publish an introduction before sale approval, with purchase disabled', async ({ page }) => {
  await page.goto('/');
  const login = await page.request.post('/api/market/login', { headers, data: { role: 'seller' } }); expect(login.ok()).toBe(true);
  const title = `판매 준비 소개 ${Date.now()}`;
  const registration = await page.request.post('/api/market/assets', { headers, multipart: {
    metadata: JSON.stringify({ title, summary: '승인 전 공개할 상품 소개입니다.', kind: 'document', version: '1.0.0', license: '내부 사용만 허용하며 재판매는 금지합니다.', limitations: ['사실성은 확인하지 않았습니다.'] }),
    file: { name: 'draft.md', mimeType: 'text/markdown', buffer: Buffer.from('# 판매 준비\n승인 전에 소개를 공개하는 흐름을 확인하는 충분한 길이의 문서입니다.\n') },
  } });
  expect(registration.ok(), await registration.text()).toBe(true);
  const { asset, version } = await registration.json();
  const content = { type: 'doc', content: [{ type: 'paragraph', content: [{ type: 'text', text: '이 상품은 판매를 준비하고 있습니다.' }] }] };
  const meta = { title, summary: '승인 전 공개된 상품 소개입니다.', purpose: '문서 작성', supportedTools: ['Codex'], contents: ['draft.md'], prerequisites: '텍스트 편집기', installation: '문서를 읽습니다.', usageTerms: version.license };
  const save = await page.request.post('/api/market/story/save', { headers, data: { assetId: asset.id, meta, content } }); expect(save.ok(), await save.text()).toBe(true);
  const publish = await page.request.post('/api/market/story/publish', { headers, data: { assetId: asset.id } }); expect(publish.ok(), await publish.text()).toBe(true);
  const catalog = await (await page.request.get('/api/market/catalog')).json();
  const listed = catalog.items.find((item: { asset: { id: string } }) => item.asset.id === asset.id);
  expect(listed?.version.id).toBe(version.id);
  expect(listed?.version.state).toBe('draft');
  expect(listed?.offer).toBeUndefined();
  const product = await (await page.request.get(`/api/market/product/${asset.id}`)).json();
  expect(product.story.content).toEqual(content);
  expect(product.item.asset.summary).toBe(meta.summary);
  expect(product.unavailableReason).toBe('판매 승인 전입니다.');
  const buyerLogin = await page.request.post('/api/market/login', { headers, data: { role: 'buyer' } }); expect(buyerLogin.ok()).toBe(true);
  const download = await page.request.get(`/api/market/download/${version.id}`);
  expect(download.status()).not.toBe(200);
  await page.goto(`/products/${asset.id}`);
  await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '구매 불가' })).toBeDisabled();
  await expect(page.locator('.purchase-bar')).toContainText('판매 승인 전입니다.');
});

test('seller draft, private media, preview and publication keep public copy separate', async ({ page }) => {
  await page.goto('/');
  const login = await page.request.post('/api/market/login', { headers, data: { role: 'seller' } }); expect(login.ok()).toBe(true);
  const suffix = Date.now().toString();
  const title = `소개 시험 ${suffix}`;
  const metadata = { title, summary: '판매자 소개 편집을 확인하는 문서 상품입니다.', kind: 'document', version: '1.0.0', license: '개인 또는 팀 내부에서 사용할 수 있으며 재판매는 허용하지 않습니다.', limitations: ['본문 사실성은 평가하지 않았습니다.'] };
  const registration = await page.request.post('/api/market/assets', { headers, multipart: { metadata: JSON.stringify(metadata), file: { name: 'sample.md', mimeType: 'text/markdown', buffer: Buffer.from('# 소개 시험\n이 문서는 판매자 소개 편집과 공개 기능을 확인하는 충분히 긴 내용의 샘플입니다. 재판매할 수 없고 추가 실행 도구가 필요하지 않습니다.\n') } } });
  expect(registration.ok(), await registration.text()).toBe(true);
  const { asset, version } = await registration.json();
  const evaluated = await page.request.post('/api/market/evaluate', { headers, data: { versionIds: [version.id] } }); expect(evaluated.ok(), await evaluated.text()).toBe(true);
  const publishedVersion = await page.request.post('/api/market/publish', { headers, data: { versionId: version.id, sellerAmount: '9', platformFee: '1', maxDiscount: '0', validDays: 30 } }); expect(publishedVersion.ok(), await publishedVersion.text()).toBe(true);
  const meta = { title, summary: '공개 전에는 보이지 않아야 하는 새 상품 소개입니다.', purpose: '문서 작성', supportedTools: ['Codex'], contents: ['sample.md'], prerequisites: 'UTF-8 편집기', installation: '파일을 내려받아 읽습니다.', usageTerms: version.license };
  const content = { type: 'doc', content: [{ type: 'heading', attrs: { level: 2 }, content: [{ type: 'text', text: '사용 방법' }] }, { type: 'paragraph', content: [{ type: 'text', text: '순서대로 파일을 확인하세요.' }] }, { type: 'video', attrs: { src: 'https://youtu.be/dQw4w9WgXcQ' } }] };
  const rejected = await page.request.post('/api/market/story/save', { headers, data: { assetId: asset.id, meta, content: { type: 'doc', content: [{ type: 'paragraph', html: '<script>alert(1)</script>' }] } } }); expect(rejected.status()).toBe(400);
  const spoof = await page.request.post('/api/market/media/upload', { headers, multipart: { assetId: asset.id, file: { name: 'fake.png', mimeType: 'image/png', buffer: Buffer.from('<svg onload="alert(1)"/>') } } }); expect(spoof.status()).toBe(400);
  const upload = await page.request.post('/api/market/media/upload', { headers, multipart: { assetId: asset.id, file: { name: 'real.png', mimeType: 'image/png', buffer: tinyPng } } }); expect(upload.ok(), await upload.text()).toBe(true);
  const { media, url } = await upload.json();
  const draftContent = { ...content, content: [...content.content, { type: 'image', attrs: { src: url, alt: '설명 그림' } }] };
  const saved = await page.request.post('/api/market/story/save', { headers, data: { assetId: asset.id, meta: { ...meta, coverMediaId: media.id }, content: draftContent } }); expect(saved.ok(), await saved.text()).toBe(true);
  const before = await (await page.request.get(`/api/market/product/${asset.id}`)).json(); expect(before.story).toBeNull(); expect(before.item.asset.summary).toBe(metadata.summary);
  const other = await page.request.post('/api/market/login', { headers, data: { role: 'seller2' } }); expect(other.ok()).toBe(true);
  expect((await page.request.get(`/api/market/story/${asset.id}`)).status()).toBe(400);
  expect((await page.request.get(`/api/market/media/${media.id}`)).status()).toBe(404);
  expect((await page.request.post('/api/market/story/publish', { headers, data: { assetId: asset.id } })).status()).toBe(400);
  await page.request.post('/api/market/login', { headers, data: { role: 'seller' } });
  const publish = await page.request.post('/api/market/story/publish', { headers, data: { assetId: asset.id } }); expect(publish.ok(), await publish.text()).toBe(true);
  const product = await (await page.request.get(`/api/market/product/${asset.id}`)).json(); expect(product.story.content).toEqual(draftContent); expect(product.item.asset.summary).toBe(meta.summary);
  const mediaPublic = await page.request.get(`/api/market/media/${media.id}`); expect(mediaPublic.ok()).toBe(true); expect(mediaPublic.headers()['content-type']).toBe('image/png');
  await page.goto('/');
  await page.getByRole('button', { name: '판매자 작업실', exact: true }).click();
  await page.getByRole('button', { name: `${title} 소개 편집` }).click();
  await expect(page.getByRole('heading', { name: `${title} 소개 작성` })).toBeVisible();
  await expect(page.getByLabel('짧은 소개')).toHaveValue(meta.summary);
  await page.getByRole('button', { name: '미리보기', exact: true }).click();
  await expect(page.getByRole('heading', { name: '상품 소개 미리보기' })).toBeVisible();
  const revised = { ...meta, summary: '초안만 바꾸고 공개 내용은 그대로 유지하는 새 소개입니다.' };
  await page.getByLabel('짧은 소개').fill(revised.summary);
  await page.locator('.editor-content .tiptap').fill('편집기에서 저장한 실제 본문입니다.');
  await page.locator('.file-button input[type=file]').setInputFiles({ name: 'real.png', mimeType: 'image/png', buffer: tinyPng });
  await expect(page.getByText('이미지를 올렸습니다. 초안을 저장해야 본문에 반영됩니다.')).toBeVisible();
  page.once('dialog', dialog => void dialog.accept('https://youtu.be/dQw4w9WgXcQ'));
  await page.getByRole('button', { name: '영상 링크' }).click();
  const saveResponse = page.waitForResponse(r => r.url().endsWith('/api/market/story/save'));
  await page.getByRole('button', { name: '초안 저장' }).click();
  const saveAgain = await saveResponse; expect(saveAgain.ok(), await saveAgain.text()).toBe(true);
  const stillPublic = await (await page.request.get(`/api/market/product/${asset.id}`)).json(); expect(stillPublic.item.asset.summary).toBe(meta.summary);
  await page.reload();
  await page.getByRole('button', { name: '판매자 작업실', exact: true }).click();
  await page.getByRole('button', { name: `${title} 소개 편집` }).click();
  await expect(page.getByLabel('짧은 소개')).toHaveValue(revised.summary);
  await expect(page.locator('.editor-content')).toContainText('편집기에서 저장한 실제 본문입니다.');
  await page.getByRole('button', { name: '소개 공개' }).click();
  await expect(page.getByText('상품 소개를 공개했습니다.')).toBeVisible();
  const finalProduct = await (await page.request.get(`/api/market/product/${asset.id}`)).json(); expect(finalProduct.item.asset.summary).toBe(revised.summary);
});
