'use client';
import { useEffect, useState } from 'react';
import type { CatalogItem, ProductStoryMeta, StoryNode } from '../domain/model';
import { api } from '../client/api';
import { buyWithWallet, connectWallet, receiveTestCredits } from '../client/wallet';
import { StoryContent } from './story-content';
import { Modal } from './modal';

type ProductResponse = { item: CatalogItem; claimed: boolean; unavailableReason: string | null; story: { content: StoryNode; meta: ProductStoryMeta; publishedAt: string } | null };
export function ProductDetail({ id }: { id: string }) {
  const [data, setData] = useState<ProductResponse | null>(null), [session, setSession] = useState<{ user: { id: string; name: string } | null; local: boolean } | null>(null);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(''), [message, setMessage] = useState('');
  const [loginOpen, setLoginOpen] = useState(false), [email, setEmail] = useState(''), [password, setPassword] = useState(''), [checkout, setCheckout] = useState<any>(null), [accepted, setAccepted] = useState(false);
  const [pendingAction, setPendingAction] = useState<'claim' | 'purchase' | null>(null);
  async function refresh() { const [product, auth] = await Promise.all([api<ProductResponse>(`product/${id}`), api<{ user: { id: string; name: string } | null; local: boolean }>('session')]); setData(product); setSession(auth); }
  useEffect(() => { refresh().catch(e => setError(e.message)).finally(() => setLoading(false)); }, [id]);
  async function act(fn: () => Promise<void>) { setBusy(true); setError(''); setMessage(''); try { await fn(); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : '처리하지 못했습니다.'); } finally { setBusy(false); } }
  async function claim() { if (!data) return; if (!session?.user) { setPendingAction('claim'); setLoginOpen(true); return; } await act(async () => { await api('free/claim', { versionId: data.item.version.id }); setMessage('보관함에 저장했습니다. ZIP과 설치 안내를 확인하세요.'); }); }
  async function purchase() { if (!data) return; if (!session?.user) { setPendingAction('purchase'); setLoginOpen(true); return; } await act(async () => { setCheckout(await api('quote', { versionIds: [data.item.version.id] })); setAccepted(false); }); }
  async function login(role?: string, signup = false) { await act(async () => { const result = await api<{ message?: string }>('login', role ? { role } : { email, password, signup }); if (result.message) { setMessage(result.message); return; } setLoginOpen(false);
    if (pendingAction === 'claim' && data) { await api('free/claim', { versionId: data.item.version.id }); setMessage('보관함에 저장했습니다. ZIP과 설치 안내를 확인하세요.'); }
    if (pendingAction === 'purchase' && data) { setCheckout(await api('quote', { versionIds: [data.item.version.id] })); setAccepted(false); }
    setPendingAction(null);
  }); }
  const item = data?.item, asset = item?.asset, version = item?.version, report = item?.report;
  const price = version?.freePackage ? '무료' : item?.offer ? `${(BigInt(item.offer.terms.sellerAmount) + BigInt(item.offer.terms.platformFee)).toString()} TEST` : '구매 불가';
  return <><header className="header"><a className="brand" href="/">AI 에셋마켓</a><nav aria-label="주 메뉴"><a href="/">둘러보기</a><a href="/?tab=library">보관함</a></nav><div className="account">{session?.user ? <><span>{session.user.name}</span>{item && !item.version.freePackage && !session.local && <><button className="secondary" disabled={busy} onClick={() => void act(async () => { await connectWallet(); setMessage('지갑을 연결했습니다.'); })}>지갑 연결</button><button className="secondary" disabled={busy} onClick={() => void act(async () => { await receiveTestCredits(); setMessage('테스트 자산을 받았습니다.'); })}>테스트 자산 받기</button></>}</> : <button className="secondary" onClick={() => setLoginOpen(true)}>로그인</button>}</div></header>
    <main className="main detail-main"><a className="back-link" href="/" onClick={e => { if (window.history.length > 1 && document.referrer.startsWith(window.location.origin)) { e.preventDefault(); window.history.back(); } }}>← 둘러보기로 돌아가기</a>
      {loading && <p>상품을 불러오는 중입니다.</p>}{error && <p role="alert" className="notice error">{error}</p>}{message && <p role="status" className="notice">{message}</p>}
      {item && asset && version && <><div className="detail-hero"><div className="detail-head"><span className="tag">{version.freePackage ? '무료 패키지' : asset.kind === 'skill' ? 'Skill' : '문서'}</span><h1>{asset.title}</h1><p className="seller-byline">{version.freePackage ? 'AI 에셋마켓 운영팀' : `판매자 ${asset.sellerName ?? asset.ownerId.slice(0, 8)}`}</p><p className="detail-summary">{asset.summary}</p></div><img className="detail-cover" src={asset.coverPath || '/covers/default.svg'} alt={asset.coverPath ? `${asset.title} 대표 이미지` : '기본 상품 표지'} /></div>
        <section className="detail-section" aria-labelledby="included"><h2 id="included">구성과 사용 정보</h2><dl className="detail-facts"><div><dt>지원 도구</dt><dd>{asset.supportedTools?.join(', ') || version.allowedTools?.join(', ') || '별도 정보 없음'}</dd></div><div><dt>버전</dt><dd>{version.version}</dd></div><div><dt>구성품</dt><dd>{asset.contents?.length ? <ul>{asset.contents.map(s => <li key={s}>{s}</li>)}</ul> : version.fileName}</dd></div><div><dt>필수 조건</dt><dd>{asset.prerequisites || version.environment}</dd></div><div><dt>설치 방법</dt><dd className="pre-wrap">{asset.installation || (version.freePackage ? 'ZIP을 받은 뒤 README.ko.md에서 Codex·Claude Code 프로젝트별 설치 경로를 확인하세요.' : '보관함의 버전별 사용 안내를 확인하세요.')}</dd></div><div><dt>이용 조건</dt><dd className="pre-wrap">{version.license}</dd></div></dl></section>
        <section className="detail-section seller-story" aria-labelledby="seller-description"><div className="section-title"><div><h2 id="seller-description">상품 소개</h2><p>판매자 작성 내용</p></div></div>{data.story ? <StoryContent content={data.story.content} /> : version.freePackage ? <><p>{asset.summary}</p><h3>한국어 사용 순서</h3><p>{version.packageKey === 'design-starter' ? '요구사항 정리 → 색상·타이포·구조 선택 → 화면 디자인' : version.packageKey === 'landing-page' ? '제품 소개 구성 → 화면 제작 → 검색 노출 요소와 주요 동작 확인' : version.packageKey === 'dashboard' ? '지표·정보 구조 정리 → 차트·표·필터 구성 → 화면 동작 확인' : '개인·브랜드 분위기 선택 → 작품 소개 화면 구성 → 반응형·링크 확인'}</p><p>ZIP에 설치 안내와 복사할 시작 프롬프트가 들어 있습니다.</p></> : <p className="muted">판매자가 아직 긴 소개를 공개하지 않았습니다.</p>}</section>
        <section className="detail-section inspection" aria-labelledby="inspection-title"><div className="section-title"><div><h2 id="inspection-title">사이트 검사·시험 결과</h2><p>AI 에셋마켓 작성 · 판매자 소개와 별도로 기록</p></div></div>{report ? <><div className="inspection-summary"><div><span className="tag sage">{report.accuracy.total ? `${report.accuracy.passed}/${report.accuracy.total} 항목 통과` : '업무 성능 미평가'}</span><p>{report.accuracy.task}</p></div><div><strong>주요 한계</strong><ul>{report.limitations.slice(0, 3).map(s => <li key={s}>{s}</li>)}</ul></div></div><details><summary>검사 범위·환경·일자·개별 결과 보기</summary><dl className="facts"><div><dt>환경</dt><dd>{report.environment}</dd></div><div><dt>일자</dt><dd>{new Date(report.createdAt).toLocaleDateString('ko-KR')}</dd></div><div><dt>기준</dt><dd>{report.rulesVersion}</dd></div><div><dt>검사자</dt><dd>{report.evaluator}</dd></div></dl><h3>확인한 범위</h3><ul>{report.security.scanned.map(s => <li key={s}>{s}</li>)}</ul><h3>개별 결과</h3>{report.accuracy.cases.length ? <ul>{report.accuracy.cases.map(c => <li key={c.name}>{c.passed ? '통과' : '실패'} · {c.name}: {c.detail}</li>)}</ul> : <p>업무 성능은 미평가입니다.</p>}<h3>미평가 항목</h3><ul>{report.security.untested.map(s => <li key={s}>{s}</li>)}</ul><p className="hash">파일 SHA-256: {version.fileHash}</p></details></> : <p>검사 결과가 없습니다. 이 상품은 현재 구매할 수 없습니다.</p>}</section>
      </>}
    </main>
    {item && version && <div className="purchase-bar"><div><small>{data.claimed ? '내 보관함에 있음' : data.unavailableReason ? data.unavailableReason : version.freePackage ? '무료 패키지' : '판매 가격'}</small><strong>{price}</strong></div>{data.claimed ? <a className="button-link" href="/?tab=library">보관함에서 보기</a> : version.freePackage ? <button disabled={busy} onClick={() => void claim()}>무료로 받기</button> : item.offer ? <button disabled={busy} onClick={() => void purchase()}>구매하기</button> : <button disabled title={data.unavailableReason ?? '현재 구매할 수 없습니다.'}>구매 불가</button>}</div>}
    <footer>상품 파일과 검사 범위를 확인한 뒤 사용하세요.<a className="demo-entry" href="/demo">데모로 들어가기</a></footer>
    {loginOpen && <Modal titleId="detail-login-title" onClose={() => setLoginOpen(false)}><h2 id="detail-login-title">로그인하고 계속하기</h2>{session?.local ? <div className="toolbar">{[['seller', '판매자 하나'], ['seller2', '판매자 둘'], ['buyer', '구매자']].map(([role, label]) => <button key={role} disabled={busy} onClick={() => void login(role)}>{label}</button>)}</div> : <form onSubmit={e => { e.preventDefault(); void login(); }}><p className="muted small">이메일은 로그인 아이디로 사용합니다. 인증 메일 없이 가입할 수 있습니다.</p><label>이메일<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>비밀번호<input type="password" minLength={8} value={password} onChange={e => setPassword(e.target.value)} required /></label><div className="toolbar"><button disabled={busy}>로그인</button><button type="button" className="secondary" disabled={busy} onClick={() => void login(undefined, true)}>회원가입</button></div></form>}<button className="secondary" onClick={() => setLoginOpen(false)}>닫기</button></Modal>}
    {checkout && <Modal titleId="detail-checkout-title" onClose={() => setCheckout(null)}><h2 id="detail-checkout-title">최종 구매 조건</h2><p>{asset?.title} v{version?.version}</p><p className="pre-wrap">{version?.license}</p><p className="checkout-total">총 {checkout.total} TEST</p><label className="check"><input type="checkbox" checked={accepted} onChange={e => setAccepted(e.target.checked)} />이용 조건과 금액을 확인했습니다.</label><div className="toolbar"><button disabled={busy || !accepted} onClick={() => void act(async () => { if (session?.local) await api('purchase', { versionIds: [version!.id], quoteHash: checkout.quoteHash }); else await buyWithWallet([version!.id], checkout.quoteHash); setCheckout(null); window.location.href = '/?tab=library'; })}>구매 승인</button><button className="secondary" onClick={() => setCheckout(null)}>취소</button></div></Modal>}
  </>;
}
