const origin = 'http://127.0.0.1:3100';
const session = await (await fetch(`${origin}/api/market/session`)).json();
if (!session.local) throw new Error('Reference assets may only be created in local development mode.');
async function client(role) {
  const login = await fetch(`${origin}/api/market/login`, { method: 'POST', headers: { Origin: origin, 'Content-Type': 'application/json' }, body: JSON.stringify({ role }) });
  const cookie = login.headers.get('set-cookie')?.split(';')[0];
  if (!login.ok || !cookie) throw new Error('Local login failed');
  return async (route, body) => {
    const response = await fetch(`${origin}/api/market/${route}`, body === undefined ? { headers: { Cookie: cookie } } : { method: 'POST', headers: { Origin: origin, Cookie: cookie, ...(body instanceof FormData ? {} : { 'Content-Type': 'application/json' }) }, body: body instanceof FormData ? body : JSON.stringify(body) });
    const result = await response.json();
    if (!response.ok) throw new Error(result.error);
    return result;
  };
}
const seller = await client('seller'), seller2 = await client('seller2'), buyer = await client('buyer');
const license = '개인·팀 내부 작업에 사용할 수 있는 플랫폼 제작 예제입니다. 원문 재판매와 공개 재배포는 허용하지 않습니다. 구매한 버전만 제공하며, TEST에는 금전적 가치가 없습니다.';
async function create(api, title, description, tools, price, document) {
  const workspace = await api('workspace');
  const existing = workspace.assets.find(a => a.title === title);
  if (existing) return workspace.versions.find(v => v.assetId === existing.id && v.version === '1.0.0');
  const kind = document ? 'document' : 'skill';
  const content = document ?? JSON.stringify({ schemaVersion: 1, steps: tools.map(tool => ({ tool })) }, null, 2);
  const form = new FormData();
  form.set('metadata', JSON.stringify({ title, summary: description, kind, version: '1.0.0', license, limitations: ['플랫폼이 제작한 작동 확인용 예제입니다. 실제 업무 품질을 보장하지 않습니다.', document ? '문서 내용의 전문성·사실성과 AI 답변 개선 효과는 미평가입니다.' : 'market-tools/1.0.0 도구만 사용합니다. 규칙 밖의 사례는 탐지·처리하지 못합니다.'] }));
  form.set('file', new Blob([content], { type: 'application/octet-stream' }), document ? 'reference.md' : 'skill.json');
  const { version } = await api('assets', form);
  await api('evaluate', { versionIds: [version.id] });
  await api('publish', { versionId: version.id, sellerAmount: String(price), platformFee: '10', maxDiscount: '5', validDays: 30 });
  return version;
}
const a = await create(seller, '[예제] 코드 위험 패턴 점검', '공개 예제. 코드에서 세 가지 위험 패턴을 찾아 JSON으로 제공합니다. 별칭·난독화와 전체 취약점 분석은 지원하지 않습니다.', ['code.review'], 90);
const b = await create(seller2, '[예제] 점검·집계 보고서', '공개 예제. 코드 점검과 데이터 집계 JSON을 마크다운 보고서로 바꿉니다. 새로운 분석을 추가하지 않습니다.', ['report.markdown'], 90);
await create(seller, '[예제] 코드 점검과 보고서 단품', '공개 예제. 코드 점검부터 보고서까지 한 단품으로 수행합니다. 단품이 충분할 때 세트보다 먼저 추천되는지 확인할 수 있습니다.', ['code.review', 'report.markdown'], 140);
await create(seller2, '[예제] 그룹별 CSV 집계', '공개 예제. group,amount 헤더와 정수 금액을 사용하는 CSV의 그룹별 합계를 구합니다. 통화 변환과 따옴표 필드는 미지원입니다.', ['csv.summarize'], 60);
await create(seller, '[예제] 결과 검토 체크리스트', '플랫폼 제작 문서 예제. AI 작업 결과를 검토할 때 사용할 질문을 정리했습니다. 내용의 전문성은 미평가입니다.', [], 20,
  '# AI 작업 결과 검토 체크리스트\n\n- 입력 데이터의 형식과 단위가 맞는지 확인합니다.\n- 결과의 근거와 원본 위치를 대조합니다.\n- 빠진 항목과 예외 조건을 기록합니다.\n- 금액과 합계는 별도 계산으로 대조합니다.\n- 자동화 도구가 지원하지 않는 상황에서는 결과를 확정하지 않습니다.\n\n이 문서는 일반적인 검토 질문의 예시이며, 특정 전문 업무의 정확성을 보장하지 않습니다.\n');
const reports = (await seller('workspace')).reports;
if (!reports.some(r => r.kind === 'combination' && r.versionIds.join(',') === [a.id, b.id].join(','))) await buyer('evaluate', { versionIds: [a.id, b.id] });
process.stdout.write('Five clearly labeled reference assets are ready. All displayed scores were generated by the evaluator.\n');
